/* eslint-disable @next/next/no-img-element */
import { useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';

import { Card } from 'components/Card';

import styles from 'styles/Home.module.css';
import useStep from 'hooks/useStep';
import { StepOne } from 'components/Steps/StepOne';
import { StepTwo } from 'components/Steps/StepTwo';

const Home: NextPage = () => {
  const [feedback, setFeedback] = useState<string | null>(null);

  const [currentStep, helpers] = useStep(2);
  const { goToNextStep } = helpers;

  const options = Array.from({ length: 5 }, (_, index) => {
    return String(index + 1);
  });

  const getStepContent = (currentStep: number) => {
    switch (currentStep) {
      case 1:
        return (
          <StepOne
            feedback={feedback}
            onFeedback={setFeedback}
            options={options}
            goToNextStep={goToNextStep}
          />
        );
      case 2:
        return <StepTwo feedback={feedback} options={options} />;
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon/png" href="/images/icon-start.svg" />
      </Head>

      <Card>{getStepContent(currentStep)}</Card>
    </div>
  );
};

export default Home;
